.PHONY:clean cleancl cleanse

CLPTH=./common/*.o ./client/*.o
SEPTH=./common/*.o ./server/*.o 
INC=./include

SERVER=./bin/server
CLIENT=./bin/client

server:

client:




#清除所有的编译产生文件
clean:
	$(RM) $(CLRPCL) $(CLRPSE)

#删除客户端的其他编译产生的文件
cleancl:
	$(RM) $(CLRPCL)

#删除服务端的其他编译产生的文件
cleanse:
	$(RM) $(CLRPSE)
